Picekl/geoclip
plantnet/malpolon pull request #54
Opened 2024-07-12 13:09 UTC by picekl

## :memo: Changelog

- [x] GeoCLIP Encoder was added as a pre-trained model.

## :link: Links
- Reference to the [Original Implementation](https://github.com/VicenteVivan/geo-clip)
## :white_check_mark: Checklist

- [x] Lint and tests pass locally with my changes
- [x] I've added the necessary DocString documentation

2024-07-19 11:00 UTC, tlarcher requested changes
location changes

2024-07-23 13:03 UTC, picekl commented on malpolon/pretrained/geoclip.py
> +@torch.jit.script
I would keep it as it is in the official implementation. It should help with optimization.

2024-07-23 14:41 UTC, tlarcher commented
The code provided looks fine to me. However before pushing it to dev, I feel like we should add an example of it in `custom_train` (no dataset, or just sample) or `benchmarks` (with dataset) first.
It will be necessary before pushing it to main anyway

2024-07-23 14:53 UTC, picekl commented
@tlarcher I agree with the "baseline example". Besides, before the merge, I would like to first finish the SatClip model as well.

2024-08-15 12:42 UTC, closed without merging